### ISSUE TITLE
`LlamaCpp` models not working with recent `llama-cpp-python` versions

### ISSUE THREAD

**Issue by JuanCSUCoder** [guidance-ai/guidance#1284]
**The bug**
I am unable to run an example code using `LlamaCpp` nor `LlamaCppChat` using the latest version of `llama-cpp-python==0.3.9`. I managed to get it working with `llama-cpp-python==0.2.38`.

From my research it seems that the attribute `llama` in `LlamaTokenizer` class was removed because of a "circular dependency issue", as stated in this [commit on llama-cpp-python repository](https://github.com/abetlen/llama-cpp-python/commit/a05d90446fea83426fe8dc0d6c78afe6c3dd0894).

Error:
```
ACTIVE MODEL PATH:  /home/juancsu/.../deepseek-r1:1.5b.gguf
llama_context: n_ctx_per_seq (512) < n_ctx_train (131072) -- the full capacity of the model will not be utilized
Traceback (most recent call last):
  File "/home/juancsu/.../error_report/main.py", line 8, in <module>
    runtime = models.LlamaCppChat(model_path, n_gpu_layers=0)
  File "/home/juancsu/miniforge3/envs/guidance-error-report/lib/python3.13/site-packages/guidance/models/_llama_cpp.py", line 142, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/juancsu/miniforge3/envs/guidance-error-report/lib/python3.13/site-packages/guidance/models/_llama_cpp.py", line 55, in __init__
    self._n_vocab = tokenizer.llama.n_vocab()
                    ^^^^^^^^^^^^^^^
AttributeError: 'LlamaTokenizer' object has no attribute 'llama'
```

**To Reproduce**
The example code I am using is the following:
```python
import os
from guidance import models, user, system, assistant, gen
from pathlib import Path

cwd = os.getcwd()
model_path = Path(os.path.join(cwd, "../deepseek-r1:1.5b.gguf"))
print("ACTIVE MODEL PATH: ", model_path)
runtime = models.LlamaCppChat(model_path, n_gpu_layers=0)
with system():
  lm = runtime + "You are a very smart assistant."
with user():
  lm += "How are you?"
with assistant():
  lm += gen(name="answer", max_tokens=40, temperature=1.0)

print("Guidance result: " + str(lm["answer"]))
```
Also here is the conda `environment.yaml`:
```yaml
name: guidance-error-report
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - adwaita-icon-theme=48.1=unix_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.13=py313h8060acc_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.9.0=pyh29332c3_0
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.38.0=h04ea711_2
  - attrs=25.3.0=pyh71513ae_0
  - brotli-python=1.1.0=py313h46c70d0_3
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - cachetools=6.1.0=pyhd8ed1ab_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.6.15=pyhd8ed1ab_0
  - cffi=1.17.1=py313hfab6e84_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cryptography=45.0.4=py313h6556f6e_0
  - dbus=1.16.2=h3c4dab8_0
  - diskcache=5.6.3=pyhd8ed1ab_1
  - distro=1.9.0=pyhd8ed1ab_1
  - epoxy=1.5.10=h166bdaf_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=ha770c72_1
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.6.0=py313h61b7b33_0
  - gdk-pixbuf=2.42.12=hb9ae30d_0
  - glib-tools=2.84.2=h4833e2c_0
  - gptcache=0.1.44=pyhd8ed1ab_1
  - graphite2=1.3.14=h5888daf_0
  - graphviz=13.0.1=hcae58fd_0
  - gtk3=3.24.43=h0c6a113_5
  - gts=0.7.6=h977cf35_4
  - guidance=0.1.5=pyhd8ed1ab_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.2.1=h3beb420_0
  - hicolor-icon-theme=0.17=ha770c72_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - jiter=0.10.0=py313h920b4c0_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h1423503_5
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=32_h59b9bed_openblas
  - libcblas=3.9.0=32_he106b2a_openblas
  - libcups=2.3.3=hb8b1518_5
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgd=2.3.3=h6f5c62b_11
  - libgfortran=15.1.0=h69a702a_3
  - libgfortran5=15.1.0=hcea5267_3
  - libglib=2.84.2=h3618099_0
  - libgomp=15.1.0=h767d61c_3
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=32_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_0
  - libpng=1.6.49=h943b412_0
  - librsvg=2.58.4=he92a37e_3
  - libsqlite=3.50.1=h6cd9bfd_7
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libtiff=4.7.0=hf01ce69_5
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxkbcommon=1.10.0=h65c71a3_0
  - libxml2=2.13.8=h4bc477f_0
  - libzlib=1.3.1=hb9d3cd8_2
  - msal=1.32.3=pyhd8ed1ab_0
  - multidict=6.5.1=py313h8060acc_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - numpy=2.3.0=py313h17eae1a_0
  - openai=1.91.0=pyhd8ed1ab_0
  - openssl=3.5.0=h7b32b05_1
  - ordered-set=4.1.0=pyhd8ed1ab_1
  - pango=1.56.3=h9ac818e_1
  - pcre2=10.45=hc749103_0
  - pip=25.1.1=pyh145f28c_0
  - pixman=0.46.2=h29eaf8c_0
  - platformdirs=4.3.8=pyhe01879c_0
  - propcache=0.3.1=py313h8060acc_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.7=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py313h4b2b08d_0
  - pydot=4.0.1=py313h78bf25f_0
  - pyformlang=1.0.10=pyhd8ed1ab_1
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.5=hec9711d_102_cp313
  - python_abi=3.13=7_cp313
  - readline=8.2=h8c095d6_2
  - regex=2024.11.6=py313h536fd9c_0
  - requests=2.32.4=pyhd8ed1ab_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - tiktoken=0.9.0=py313h3f234b3_0
  - tk=8.6.13=noxft_hd72426e_102
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.14.0=h32cad80_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.14.0=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_1
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - yarl=1.20.1=py313h8060acc_0
  - zstandard=0.23.0=py313h536fd9c_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - jinja2==3.1.6
      - llama-cpp-python==0.3.9
      - markupsafe==3.0.2
prefix: /home/juancsu/miniforge3/envs/guidance-error-report
```

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): Ubuntu 24.04.2 LTS with Linux 6.11.0-26-generic
 - Guidance Version (`guidance.__version__`): '0.1.5'

**Comment by testonlyinprod** [comment]
Hi @JuanCSUCoder thanks for the issue!

Try `pip install -U guidance` and see how it works on `0.2.3`. Let us know if you're still seeing the same problem.

**Comment by jovemexausto** [comment]
Hi,

I observed that the original issue discussed the OP using `guidance` v0.1.5, and @nopdive's response resolved it, confirming that `guidance` v0.2.3 works well with `llama-cpp-python` v0.3.9. However, recent updates to `llama-cpp-python`, aligning with changes in `llama.cpp`, have caused new compatibility issues with the latest `guidance` version. While the title of the existing issue is relevant, I believe opening a new issue is better to clearly address this distinct problem.

Here is the issue with a detailed description: #1306

**Comment by jovemexausto** [comment]
Hi,

I observed that the original issue discussed the OP using `guidance` v0.1.5, and it’s likely that @nopdive’s reply addressed the issue, as `guidance` v0.2.3 works well with `llama-cpp-python` v0.3.9. However, recent updates to `llama-cpp-python`, aligning with changes in `llama.cpp`, have caused new compatibility issues with the latest `guidance` version. While the title of the existing issue is relevant, I believe opening a new issue is better to clearly address this distinct problem.

Here is the issue with a detailed description: #1306

**Comment by hudson-ai** [comment]
Closing due to reasons outlined above -- please feel free to re-open if you continue to have issues after #1306 is resolved
