### ISSUE TITLE
No example work with 0.3.0

### ISSUE THREAD

**Issue by hrazmsft** [guidance-ai/guidance#1402]
**The bug**
No example work with 0.3.0:
- HTML Build example in `README.md` (erros with args names)
- guaranteeing_valid_syntax.ipynb (error `generate_character() takes from -2 to 1 positional arguments but 2 were given`)
- https://guidance.readthedocs.io/en/latest/example_notebooks/tutorials/code_generation.html (error `ImportError: cannot import name 'will_gen' from 'guidance.library._gen' (D:\sources\AgentServer\.venv\Lib\site-packages\guidance\library\_gen.py)`)

**To Reproduce**
To reproduce, just copy paste each example above in your favorite IDE and try to run.

For example:
```python
import guidance

# Define the model we will use
# lm = guidance.models.LlamaCpp("/path/to/model.gguf", n_gpu_layers=-1)
lm = guidance.models.Transformers("microsoft/Phi-3-mini-4k-instruct")

from guidance import gen, select

# we can pre-define valid option sets
sample_weapons = ["sword", "axe", "mace", "spear", "bow", "crossbow"]
sample_armor = ["leather", "chainmail", "plate"]

# define a re-usable "guidance function" that we can use below
@guidance
def quoted_list(lm, name, n):
    for i in range(n):
        if i > 0:
            lm += ", "
        lm += '"' + gen(name, list_append=True, stop='"') + '"'
    return lm

@guidance
def generate_character(
    lm,
    character_one_liner,
    weapons: list[str] = sample_weapons,
    armour: list[str] = sample_armor,
    n_items: int = 3
):
    lm += f'''\
    {{
        "description" : "{character_one_liner}",
        "name" : "{gen("character_name", stop='"')}",
        "age" : {gen("age", regex="[0-9]+")},
        "armour" : "{select(armour, name="armor")}",
        "weapon" : "{select(weapons, name="weapon")}",
        "class" : "{gen("character_class", stop='"')}",
        "mantra" : "{gen("mantra", stop='"')}",
        "strength" : {gen("age", regex="[0-9]+")},
        "quest_items" : [{quoted_list("quest_items", n_items)}]
    }}'''
    return lm


generation = lm + generate_character("A quick and nimble fighter")
```
(From https://github.com/guidance-ai/guidance/blob/main/notebooks/guaranteeing_valid_syntax.ipynb)

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): Windows 11
 - Guidance Version (`guidance.__version__`): 0.3.0

**Comment by nking-1** [comment]
I was able to reproduce the issue with the `code_generation` notebook (cannot import name 'will_gen') but was not able to reproduce the other issues regarding positional arguments. My setup does differ slightly from yours in that I am running Mac OS. 

Perhaps there is something wrong with your python environment which is causing the issue. Consider running `pip freeze` as well as dumping your specific python version with `python -c "import sys; print(sys.version)"` and reporting it here.

We will look into fixing the issue with `will_gen`. Thank you for reporting it.

**Comment by xXMrNidaXx** [comment]
The 0.3.0 release has significant API changes from 0.2.x. Here's a quick migration guide:

**Key changes in 0.3.0:**

1. **Model loading:**
```python
# Old (0.2.x)
import guidance
guidance.llm = guidance.llms.OpenAI('gpt-4')

# New (0.3.0)
from guidance import models
model = models.OpenAI('gpt-4')
```

2. **Program execution:**
```python
# Old
program = guidance('''...''')
result = program(variable=value)

# New (0.3.0)
from guidance import gen, select
with model:
    model += 'Your prompt here'
    model += gen('output', max_tokens=100)
```

3. **Select syntax:**
```python
# Old
{{select 'choice' options=['a', 'b', 'c']}}

# New
model += select(['a', 'b', 'c'], name='choice')
```

**Quick fix for most examples:**
- Replace `guidance.llm =` with model instantiation
- Use context manager (`with model:`) pattern
- Update template syntax to function calls

Check the migration guide in docs for more details.

**Comment by nking-1** [comment]
This notebook should work now that https://github.com/guidance-ai/guidance/pull/1465 is merged. Please let us know if you still have issues.
